---
- name: Test
  hosts: all
  gather_facts: no
  vars:
    # 默认不备份，可通过 -e bak=true 覆盖
    bak: false
    target_path: "{{ target }}"   # 对应脚本中的 Target

  tasks:
    - name: 检查必要变量是否已定义
      assert:
        that:
          - dir is defined
          - target is defined
        fail_msg: "必须提供 'dir' 和 'target' 变量。"