---
- name: 部署应用目录到远程主机
  hosts: all
  gather_facts: no
  vars:
    # 默认不备份，可通过 -e bak=true 覆盖
    bak: false
    target_path: "{{ target }}"   # 对应脚本中的 Target
    local_dist_path: "../dist/{{ dir }}"

  tasks:
    # - name: 检查必要变量是否已定义
    #   assert:
    #     that:
    #       - dir is defined
    #       - target is defined
    #     fail_msg: "必须提供 'dir' 和 'target' 变量。"

    # - name: 获取当前时间戳
    #   set_fact:
    #     timestamp: "{{ lookup('pipe', 'date +%F-%H-%M') }}"
    #     tmp_dir_name: "{{ dir }}-{{ lookup('pipe', 'date +%F-%H-%M') }}"


    # - name: 如果启用了备份，则重命名当前目录为备份
    #   command: mv "{{ target_path }}/{{ dir }}" "{{ target_path }}/{{ tmp_dir_name }}"
    #   when: bak | bool
    #   args:
    #     chdir: "{{ target_path }}"
    #     creates: "{{ target_path }}/{{ tmp_dir_name }}"  # 避免重复执行

    # - name: 如果未启用备份，则删除当前目录
    #   file:
    #     path: "{{ target_path }}/{{ dir }}"
    #     state: absent
    #   when: not (bak | bool)

    # - name: 将本地 dist 目录复制到远程主机的 /tmp 目录
    #   copy:
    #     src: "{{ local_dist_path }}/"
    #     dest: "{{ target_path }}/{{ dir }}/"
    #     directory_mode: yes
    #     mode: '0755'

    - name: 列出目标目录内容（用于验证）
      command: ls -l "{{ target_path }}"
      register: ls_result
      changed_when: false

    - name: 显示目录列表
      debug:
        msg: "{{ ls_result.stdout_lines }}"